#!/usr/bin/env bash

message=$(cat $1)

types="build|ci|chore|docs|feat|fix|merge|perf|refactor|style|test|wip"
additional="(\n{2}(.+(\n)*)+)?"
pattern="^($types)(\([[:alpha:]\-]+\))?: .+$additional"

if [[ $message =~ $pattern ]]; then
	exit 0
fi

echo "Invalid commit message

Please follow a commit message that follows this format:

<type>([optional scope]): <description>

[optional body]

[optional footer(s)]"

exit 1
